# =============================================
# APPLICATION
# =============================================
spring.application.name=ecommerce
server.port=8090

# =============================================
# DATASOURCE - Neon PostgreSQL
# =============================================
spring.datasource.url=jdbc:postgresql://ep-still-snow-amp53gw4-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_An5POCKz3UaV
spring.datasource.driver-class-name=org.postgresql.Driver


# Connection pool (HikariCP)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# =============================================
# JPA / HIBERNATE
# =============================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.open-in-view=false

# =============================================
# JACKSON
# =============================================
spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.write-dates-as-timestamps=false